version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lamp_docker
      MYSQL_USER: lamp_docker
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './db:/docker-entrypoint-initdb.d'
    networks:
      - lamp-docker

  www:
    depends_on:
      - db
    build: ./docker/web
    volumes:
      - './:/var/www/html'
      - ./docker/web/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/web/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - 8080:80
      - 443:443  
    networks:
      - lamp-docker
    extra_hosts:
      - host.docker.internal:host-gateway
      


  phpmyadmin:
    depends_on:
      - db
      - www
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306  
    networks:
      - lamp-docker

networks:
  lamp-docker:
    driver: bridge